config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get '/about' => 'pages#about'
  root 'products#index'
  resources :users do
    resource :profile
  end
  resources :contacts
  resources :products do
    resource :show, :create, :customer
  end
  post 'quote', to: 'products#quote' 
  post '/order', to: 'products#order' 
  get 'done', to: 'products#done'
  get  '/faqs', to: 'pages#faqs'

end

app/models/charge.rb
class Charge < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: 
    "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)

        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            
            ContactMailer.contact_email(name, email, body).deliver
            
            flash[:success] = 'Message sent.'
            redirect_to new_contact_path
        else
            flash[:error] = 'Error occured, message has not been sent.'
            redirect_to new_contact_path 
        end 
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
    end
    
    def about
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index 
        @products = Product.all 
    end 
    
    def show
        @products = Product.find(params[:id])
    end
    
    def quote # code for UberRUSH shipping quote 
    end 
    
    def order # code for Stripe charge and UberRUSH delivery creation 
        customer = Stripe::Customer.create(
            :email => params[:email],
            :card  => params[:stripeToken]
        )
        
        items = [
            {
                title: params[:title],
                quantity: 1,
                price: params[:price]
            }
        ]
        
        @amount = ((params[:price].to_f + response["fee"]) * 100).to_i
    
    Stripe.api_key = "sk_test_NjOOMGCyPpGY8xvpOxjETJuy"

        # Get the credit card details submitted by the form
        token = params[:stripeToken]
    end
        # Create the charge on Stripe's servers - this will charge the user's card
        begin
        
        charge = Stripe::Charge.create(
            :customer => customer.id,
            :amount => @amount,
            :description => params[:title],
            :currency => 'usd'
        )
        
        redirect_to done_path(amount: @amount)
        
    rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to :back
    end 
    
    def done # code for confirmation page 
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user
    
    def new
        # form where a user can fill out their own profile
        @user = User.find( params[:user_id] )
        @profile = Profile.new
    end
    
    def create
        @user = User.find( params[:user_id] )
        @profile = @user.build_profile(profile_params)
        if @profile.save
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :new
        end
    end
    
    def edit
        @user = User.find( params[:user_id] )
        @profile = @user.profile
    end
    
    def update
        @user = User.find(params[:user_id] )
        @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :edit
        end
    end
    
    private
        def profile_params
            params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :contact_email, :description)
        end
    
        def only_current_user
            @user = User.find( params[:user_id] )
            redirect_to(root_url) unless @user == current_user
        end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    
    def create
        super do |resource|
            if params[:plan]
                resource.plan_id = params[:plan]
                if resource.plan_id == 3
                    resource.save_with_payment
                else
                    resource.save
                end
            end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @users = User.includes(:profile, :customer)
    end
    
    def show
        @user = User.find( params[:id] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def job_title_icon
        if @user.profile.job_title == "Independent Buyer"
            "<i class='fa fa-user'></i>".html_safe
        elsif @user.profile.job_title == "Company Representative"
            "<i class='fa fa-user-plus'></i>".html_safe
        elsif @user.profile.job_title == "Store Owner"
            "<i class='fa fa-university'></i>".html_safe
        end
    end
end

app/views/contacts/new.html.erb
<div class="container text-center">
    <p  class="h2">Questions or Comments</p>
    <p class="h3">Are greatly appreciated.</p>
</div>


<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well text-center">
         <%= form_for @contact do |f| %>
           <div class="form-group">
             <%= f.label :name %>
             <%= f.text_field :name, class:'form-control' %>
           </div>
      
           <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class:'form-control'%>
           </div>
        
           <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class:'form-control' %>
           </div>
           <%= f.submit 'submit', class: 'btn btn-default' %>
           <% end %>
        </div>
    </div>
</div>

<h2 class="text-center">What our customers say</h2>
<div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    <h4>"This company is the best. I am so happy with the result!"<br><span style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>
    </div>
    <div class="item">
      <h4>"One word... WOW!!"<br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
    </div>
    <div class="item">
      <h4>"Could I... BE any more happy with this company?"<br><span style="font-style:normal;">Chandler Bing, Actor, FriendsAlot</span></h4>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asm-Impex</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Maven+Pro:400,900' rel='stylesheet" type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Raleway:800' rel='stylesheet" type='text/css'>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/picnicss/6.1.1/picnic.min.css">
  <link href="https://api.stripe.com">
  <%= csrf_meta_tags %>
</head>
  <body class="row">
    <div class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand' do %>
           <i class="fa fa-home" aria-hidden="true"></i>
              ASM - Impex
          <% end %>
        </div>
        
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path, method: :get %></li>
            
            <!-- /.sign up / login -->
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-check"></span> Login<span class="caret"></a>
              <ul class="dropdown-menu" role="menu">
                <% if user_signed_in? %>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Sign Up", new_user_registration_path, method: :get %></li>
                  <li><%= link_to "Sign In", new_user_session_path, method: :get %></li>
                <% end %>
                <% if user_signed_in? %>
                <% if current_user.profile %>
                <li><%= link_to "Community", users_path %></li>
                <li><%= link_to "My Account", edit_user_registration_path %></li>
                <li><%= link_to "Edit Your Profile", edit_user_profile_path(current_user) %></li>
                <li><%= link_to  "View Your Profile", user_path(current_user) %></li>
                <% else %>
                <%= link_to "Create your Profile", new_user_profile_path(current_user) if current_user %>
                <% end %>
                <% end %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "FAQ's", faqs_path, method: :get %></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container">
      <% flash.each do |key, value| %>
       <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      
      <%= yield %>
    </div>
    
    <footer class="container-fluid text-center">
      <a href="#myPage" title="To Top">
        <span class="glyphicon glyphicon-chevron-up"></span>
      </a>
      <br>
      <h3><%= link_to "Contact Us", new_contact_path %></h3>
      <div class="btn-group">
        <!--Facebook-->
        <button type="button" class="btn btn-lg btn-fb"><i class="fa fa-facebook"></i></button>
        <!--Facebook-->
        <button type="button" class="btn btn-lg btn-tw"><i class="fa fa-twitter"></i></button>
        <!--Facebook-->
        <button type="button" class="btn btn-lg btn-ins"><i class="fa fa-instagram"></i></button>
      </div>
      <div class="well text-center">
        <h6>themes provided by w3schools.com</h6>
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <div class="container text-center">  
    <h1>ASM - IMPEX</h1>
    <p><b>"a quality of beauty and intensity of emotion regarded as characteristic of..."</b></p> 
    <div class="btn-group">
      <!--Facebook-->
      <button type="button" class="btn btn-lg btn-fb"><i class="fa fa-facebook"></i></button>
      <!--Facebook-->
      <button type="button" class="btn btn-lg btn-tw"><i class="fa fa-twitter"></i></button>
      <!--Facebook-->
      <button type="button" class="btn btn-lg btn-ins"><i class="fa fa-instagram"></i></button>
    </div>
  </div>
</div>

<div class="container text-center">
  <div class="col-sm-4">
    <div class="thumbnail">
      <img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQN906ZAJ0TFLU85RAjmiwDjq5ONwmsQdJ6_CCTGkinpG_N6le9ww" alt="Apparel">
      <p><strong>Clothing</strong></p>
      <p>Fashion</p>
      <a class="btn" href="/">Search</a>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="thumbnail">
      <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQlPlz2qGFGVzMiNVpkzyQXhhsyQOc38YhySQUN-g92MsqNz5ai" alt="Electronics">
      <p><strong>Electronics</strong></p>
      <p>New</p>
      <a class="btn" href="/">Search</a>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="thumbnail">
      <img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTfQqI4-Yjzvu0uBTdcYR32cRvkkm7U9kh55IoGIxDZMQwazvem" alt="Promo">
      <p><strong>Discounts</strong></p>
      <p>Bundle and Save</p>
      <a class="btn" href="/">Search</a>
    </div>
  </div>
</div>

app/views/pages/faqs.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>FAQ's</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#section1">Home</a></li>
        <li><a href="#section2">Products</a></li>
        <li><a href="#section3">Shipping</a></li>
        <li><a href="#section3">Profile</a></li>
      </ul><br>
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search Blog..">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    </div>

    <div id="section2" class="container-fluid">
        <div class="col-sm-9">
          <h4><small>ASM - Impex</small></h4>
          <hr>
          <h2>Signing In</h2>
          <h5><span class="glyphicon glyphicon-time"></span> Post by Sajj, Jul 27, 2016.</h5>
          <h5><span class="label label-danger">About</span> <span class="label label-primary">Sign In</span></h5><br>
          <p>How to create a unique sign in. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <br><br>
        </div>
    </div>
  
    <div id="section3" class="container-fluid">
        <div class="col-sm-9">      
          <h4><small>RECENT POSTS</small></h4>
          <hr>
          <h2>Order Catalog/Guide</h2>
          <h5><span class="glyphicon glyphicon-time"></span> Post by Sajj, Jul 27, 2016.</h5>
          <h5><span class="label label-success">Lorem</span></h5><br>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <hr>
        </div>
    </div>
<script>
$(document).ready(function(){
    $('body').scrollspy({target: ".navbar", offset: 50});
});
</script>

app/views/products/done.html.erb
<h1>Thank you for the order!</h1>

<p>Total Cost with Shipping: <strong><%= number_to_currency(params[:amount].to_i / 100.00) %></strong></p>

<p>A copy of the invoice has been sent to your email, and you will recieve SMS updates from the UberRUSH courier.</p>

app/views/products/index.html.erb
<div class="jumbotron">
  <div class="container text-center">
      <h1>ASM Impex</h1> 
      <p>We specialize in online-shopping</p>
      <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Welcome to Asm - Impex
        </button>
        
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Asm - Impex</h4>
              </div>
              <div class="modal-body">
                Welcome to Asm - Impex, an online store specializing in a variety of textiles, electronic promotions, and clothing/home-goods!
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
          
            
<div class="flex one three-1000">
    <% @products.each do |product| %> 
        <article class="card">
            <img src="<%= product.picture %>"> 
            <footer> 
                <h3><%= product.title %></h3>
                <%= link_to "Buy", product_path(product), class: "btn btn-default" %> 
            </footer>
        </article>
    <% end %>
</div>

app/views/products/quotes.js.erb
$('#shipping-cost').html("<%= number_to_currency(@quote["fee"]) %>"); 
$('#eta').html("<%= @quote["pickup_eta"] + @quote["dropoff_eta"] %> minutes");

$('#shipping-quote').hide(); 
$('#quote-info').show();
$('#checkout').show();

$('input[name=address]').val('<%= @dropoff[:location][:address]  %>');
$('input[name=city]').val('<%= @dropoff[:location][:city]  %>');
$('input[name=postal_code]').val('<%= @dropoff[:location][:postal_code] %>;

app/views/products/show.html.erb
<div class="row">
    <div class="flex one two-1000"> 
        <div class="product-image"> 
            <img src="<%= @product.picture %>" /> 
        </div>
    <div> 
            <h1><%= @product.title %></h1> 
            <p> 
                <%= @product.description %> 
            </p> 
                
            <h2><%= number_to_currency(@product.price) %></h2> 
            <br/> 
            
            <h3>Instant Shipping</h3> 
            <img src="https://s31.postimg.org/cjyo11eqj/uber_rush.png" class="logo"/>
            <p> 
                <small>UberRUSH is an on-demand delivery network powered by Uber. Once your order is picked up, you’ll receive a text message with a link to track your delivery in real time on the map. So you always know exactly when it will arrive. </small> 
            </p> 
            
            <div id="checkout" class="show">
                <h3>Order Product</h3>
                <%= form_tag "/order", method: 'post' do %>
                    <%= text_field_tag :first_name, nil, placeholder: "First Name" %>
                    <%= text_field_tag :last_name, nil, placeholder: "Last Name" %>
                    <%= text_field_tag :email, nil, placeholder: "Email" %>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="Shoes"
                  data-amount="">
              </script>
            <% end %>
          </div>

                     
                     <form action="/charges" method="POST" id="payment-form">
                          <script
                            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="pk_test_3eCsVdCaj6V0AwGDLkTMjtC5"
                            data-amount="@amount = params[:amount]"
                            data-name="Shopping Cart"
                            data-description="Complete Checkout"
                            data-image="/img/documentation/checkout/marketplace.png"
                            data-locale="auto">
                          </script>
                    </form>
            </div>
            
        </div> 
    </div>
</div>

app/views/profiles/_form.html.erb
 <%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    
     <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :job_title %>
        <%= f.select :job_title, ['Independent Buyer', 'Company Representative', 'Store Owner'], {}, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.submit "Update Profile", class: 'btn btn-default' %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1 class="text-center">Edit Your Profile</h1>
        <p class="text-center">Update your personal info...</p>
        <div class="well text-center">
           <%= render 'form' %>
        </div>
    </div>
</div>

app/views/profiles/form.html.erb
 <%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    
     <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :job_title %>
        <%= f.select :job_title, ['Independent Buyer', 'Company Representative', 'Store Owner'], {}, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.submit "Update Profile", class: 'btn btn-default' %>
    </div>
<% end %>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create Your Profile</h1>
        <p class="text-center">Update your personal info...</p>
        <div class="well">
            <%= form_for @profile, url: user_profile_path do |f| %>
                <div class="form-group">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :job_title %>
                    <%= f.select :job_title, ['Independent Buyer', 'Company Representative', 'Store Owner'], {}, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :contact_email %>
                    <%= f.text_field :contact_email, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :description %>
                    <%= f.text_field :description, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.submit "Update Profile", class: 'btn btn-default' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <ul class="list-unstyled">
            <% @users.each do |user| %>
                <% if user.profile %>
                 <li>
                    <div class="well">
                        <div class="col-sm-4 text-center">
                            <% if user.profile.avatar %>
                                <%= link_to user do %>
                                <%= image_tag user.profile.avatar.url(:thumb), class: 'user-index-avatar' %>
                                <% end %>
                            <% end %>
                        </div>
                    
                        <div>
                            <%= link_to user do %>    
                                <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                            <% end %>
                            <p><%= user.profile.job_title %></p>
                        </div>
                    </div>
                </li>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid text-center">
  <h3 class="margin">ASM - Impex</h3>
  <p>World-Class Industry specializing in electronics, clothing, materials, imported textiles, and much more...</p>
    <img src="http://41.media.tumblr.com/0515719099389a401818068d800450ed/tumblr_inline_nt08nbCAz81rjic88_1280.jpg" class="img-circle" alt="Cinque Terre" width="304" height="236">
</div>

<div class="col-md-6 col-md-offset-3">
  <h1 class="margin text-center"><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1><br>
  <div class="row">
    <div class="col-md-3 text-center">
    <%= image_tag @user.profile.avatar.url, class: 'user-show-avatar' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= @user.profile.description %>
    </div>
    <div class="col-md-4">
      <span class="job-title-icon"><%= job_title_icon %></span><%= @user.profile.job_title %>
    </div>  
    <div class="col-md-4">
      <%= @user.profile.contact_email %>
    </div>
  </div>
</div>

<div class="col-md-4 col-md-offset-4">
  <h2 class="margin text-center">ASM ™ Impex Community</h2>
      <div class="container-fluid text-center">
      <%= link_to "Visit the Community", users_path, class: 'btn btn-default' %>
    </div>
</div>